services:
  test_db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: test-app
    ports:
      - 8096:5432

  test_redis:
    image: redis:7-alpine  # Redis 5.0+ is required for Streams
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass password # no special setup needed for simple messaging

volumes:
  redis-data:
