networks:
  monitoring:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data
    volumes:
      - app-data:/var/lib/postgresql/data
      # Mount a local directory for custom init script
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "8095:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      # Format: postgresql://username:password@hostname:port/database?sslmode=disable
      DATA_SOURCE_NAME: "postgresql://postgres_exporter:password@db:5432/app?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - monitoring

  app:
    build: .
    ports:
      - "8090:8090" # rest api
      - "8099:8099" # grpc api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: app
      SERVER_PORT: 8090
      GRPC_PORT: 8099
      JWT_SECRET: secret
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
      
volumes:
  app-data:
  grafana-storage:
